version: '3'
services:
  bots:
    build:
      context: .
      dockerfile: Dockerfile.bots
    ports:
      - "8080:8080"
    restart: unless-stopped
    hostname: "bots"
    container_name: "my-bots"

  cronicle:
    build:
      context: .
      dockerfile: Dockerfile.cronicle
    ports:
      - "3012:3012"
    restart: unless-stopped
    hostname: "cronicle"
    container_name: "my-cronicle"
